Latest updates for 1.1.0.4

diff --git a/src/cpp/connector/gpfs/tlgpfschnode b/src/cpp/connector/gpfs/tlgpfschnode
--- a/src/cpp/connector/gpfs/tlgpfschnode
+++ b/src/cpp/connector/gpfs/tlgpfschnode
@@ -19,13 +19,16 @@ NODE_NOT_IN_CLUSTER=4
 SWITCH_FAILED=5
 STOP_FAILED=6
 LAUNCH_FAILED=7
+MON_FAILED=8
 PROGRAM_NAME=`basename $0`
 # is_enable's value: 1 for enable, 2 for disable
 is_enable=0
 # is_verbose's value: 0 for disable, 1 for enable
 is_verbose=0
-# condition name to update
+# condition name to monitor GPFS connector
 GPFS_MON_COND=GPFSConnectorMonitor
+# response name to invoke GPFS connector up/down handler
+GPFS_MON_RESP=GPFSConnectorFailed
 
 #---------------------------------------------------------------------
 # parameter 1: input, exit status
@@ -47,67 +50,30 @@ usage()
 }
 
 #---------------------------------------------------------------------
-# parameter 1: input, node to run teal agent
-# parameter 2: input, 1 for start monitor and other for stop monitor
+# parameter 1: input, node to run xdsh(MN facing name)
+# parameter 2: input, node to run teal agent(GPFS facing name)
 
-updateGPFSMonCond()
+startMonitor()
 {
-   condition=`/usr/bin/lscondition $GPFS_MON_COND 2>/dev/null`
-   if [ $? -ne 0 ]; then
-      echo "No such condition $GPFS_MON_COND found on this node, please double check!"
-      return $CONFIG_FAULT
+   cmd="/opt/xcat/bin/xdsh $1 \"/usr/bin/startcondresp $GPFS_MON_COND $GPFS_MON_RESP; echo \"rc=$?\"\""
+   msg=`eval $cmd`
+   if [ $is_verbose -eq 1 ]; then
+      echo "#######Verbose mode, messages on remote node $2 are as below######"
+      echo "command invoked is:"
+      echo "$cmd"
+      echo "output is:"
+      echo "$msg"
+      echo "###########################End of messages########################"
    fi
-   # save original selection string
-   condition=`echo "$condition" |grep SelectionString | awk -F "\""  '{i=2;while(i<NF) {printf $i;i++}}'`
-
-   # save node list
-   nodelist=`echo "$condition" | grep NodeNameList 2>/dev/null`
-   if [[ -n $nodelist ]]; then
-      nodelist=`echo "$condition" | cut -d { -f 2 | cut -d } -f 1 2>/dev/null`
-   fi
-
-   # if no node list
-   if [[ -z $nodelist ]]; then
-      if [ $2 -eq 1 ]; then
-         `/usr/bin/chcondition -s "ProgramName==\"tlgpfsmon\" && NodeNameList |< {'$1'}" $GPFS_MON_COND >/dev/null 2>&1`
-         if [ $? -ne 0 ]; then
-            echo "Update condition $GPFS_MON_COND to start monitor failed for node $1!"
-            # recover to the original one
-            `/usr/bin/chcondition -s "$condition" $GPFS_MON_COND >/dev/null 2>&1`
-            return $CONFIG_FAULT
-         fi
-      fi
+   rec=`echo "$msg" | grep rc= | cut -d '=' -f2`
+   # return code will be 0 if start succeeds or already started
+   if [ $rec -eq $SUCCESS ]; then
+      echo "Monitoring of GPFS connector is started..."
       return $SUCCESS
-   fi
-
-   # remove $1 from node list
-   nodelist=`echo "$nodelist" | sed "s/'$1',//g" | sed "s/,'$1'//g" | sed "s/'$1'//g" 2>/dev/null`
-   if [ $2 -eq 1 ]; then
-      if [[ -z $nodelist ]]; then
-         `/usr/bin/chcondition -s "ProgramName==\"tlgpfsmon\" && NodeNameList |< {'$1'}" $GPFS_MON_COND >/dev/null 2>&1`
-      else
-         `/usr/bin/chcondition -s "ProgramName==\"tlgpfsmon\" && NodeNameList |< {$nodelist,'$1'}" $GPFS_MON_COND >/dev/null 2>&1`
-      fi
-      if [ $? -ne 0 ]; then
-         echo "Update condition $GPFS_MON_COND to start monitor failed for node $1!"
-         # recover to the original one
-         `/usr/bin/chcondition -s "$condition" $GPFS_MON_COND >/dev/null 2>&1`
-         return $CONFIG_FAULT
-      fi
    else
-      if [[ -z $nodelist ]]; then
-         `/usr/bin/chcondition -s "ProgramName==\"tlgpfsmon\"" $GPFS_MON_COND >/dev/null 2>&1`
-      else
-         `/usr/bin/chcondition -s "ProgramName==\"tlgpfsmon\" && NodeNameList |< {$nodelist}" $GPFS_MON_COND >/dev/null     2>&1`
-      fi
-      if [ $? -ne 0 ]; then
-         echo "Update condition $GPFS_MON_COND to stop monitor failed for node $1!"
-         # recover to the original one
-         `/usr/bin/chcondition -s "$condition" $GPFS_MON_COND >/dev/null 2>&1`
-         return $CONFIG_FAULT
-      fi
+      echo "Start monitoring GPFS connector failed..."
+      return $MON_FAILED
    fi
-   return $SUCCESS
 }
 
 #---------------------------------------------------------------------
@@ -116,20 +82,16 @@ updateGPFSMonCond()
 
 launchCollector()
 {
-   # update GFPS connector monitor condition at first
-   updateGPFSMonCond $1 1
-   if [ $? -ne 0 ]; then
-      return $CONFIG_FAULT
-   fi
+   cmd="/opt/xcat/bin/xdsh $1 \"export TEAL_CONN_LOG_LEVEL=$TEAL_CONN_LOG_LEVEL; export TEAL_LOG_DIR=$TEAL_LOG_DIR; export TLGPFS_CONF=$TLGPFS_CONF; export POLLING_INTERVAL=$POLLING_INTERVAL; /usr/lpp/mmfs/bin/mmchnode --teal-agent -N $2; echo rc=$?\""
+   msg=`eval $cmd`
    if [ $is_verbose -eq 1 ]; then
-      msg=`/opt/xcat/bin/xdsh $1 "export TEAL_CONN_LOG_LEVEL=$TEAL_CONN_LOG_LEVEL; export TEAL_LOG_DIR=$TEAL_LOG_DIR; export TLGPFS_CONF=$TLGPFS_CONF; export POLLING_INTERVAL=$POLLING_INTERVAL; /usr/lpp/mmfs/bin/mmchnode --teal-agent -N $2; echo rc=$?"`
-      echo "#######Verbose mode, messages on sevice node $2 are as below######"
+      echo "#######Verbose mode, messages on remote node $2 are as below######"
+      echo "command invoked is:"
+      echo "$cmd"
+      echo "output is:"
       echo "$msg"
       echo "###########################End of messages########################"
-   else
-      msg=`/opt/xcat/bin/xdsh $1 "export TEAl_CONN_LOG_LEVEL=$TEAL_CONN_LOG_LEVEL; export TEAL_LOG_DIR=$TEAL_LOG_DIR; export TLGPFS_CONF=$TLGPFS_CONF; export POLLING_INTERVAL=$POLLING_INTERVAL; /usr/lpp/mmfs/bin/mmchnode --teal-agent -N $2 >/dev/null 2>&1; echo rc=$?" 2>/dev/null`
    fi
-
    rec=`echo "$msg" | grep rc= | cut -d '=' -f2`
    if [ $rec -ne 0 ]; then
       echo "mmchnode failed to start teal agent on $2..."
@@ -139,6 +101,11 @@ launchCollector()
    isLaunched=`echo "$isLaunched" | head -1 |  tr -d ' ' | cut -d':' -f2`
    if [ $isLaunched -ne 0 ]; then
       echo "Launched teal agent on $2 successfully."
+      echo "Start to monitoring GPFS connector..."
+      startMonitor $1 $2
+      if [ $? -ne 0 ]; then
+         echo "Can not start monitoring GPFS connector correctly, may miss GPFS connector up/down events..."
+      fi
       return $SUCCESS
    fi
    echo "Launching teal agent on $2 failed."
@@ -151,25 +118,29 @@ launchCollector()
 
 stopCollector()
 {
+   cmd="/opt/xcat/bin/xdsh $1 \"/usr/lpp/mmfs/bin/mmchnode --noteal-agent -N $2; echo rc=$?\""
+   msg=`eval $cmd`
    if [ $is_verbose -eq 1 ]; then
-      msg=`/opt/xcat/bin/xdsh $1 "/usr/lpp/mmfs/bin/mmchnode --noteal-agent -N $2; echo rc=$?"`
-      echo "#######Verbose mode, messages on sevice node $2 are as below######"
+      echo "#######Verbose mode, messages on remote node $2 are as below######"
+      echo "command invoked is:"
+      echo "$cmd"
+      echo "output is:"
       echo "$msg"
       echo "###########################End of messages########################"
-   else
-      msg=`/opt/xcat/bin/xdsh $1 "/usr/lpp/mmfs/bin/mmchnode --noteal-agent -N $2 >/dev/null 2>&1; echo rc=$?" 2>/dev/null`
    fi
    rec=`echo "$msg" | grep rc= | cut -d '=' -f2`
    if [ $rec -ne 0 ]; then
       echo "mmchnode failed to stop teal agent on $2..."
       return $LAUNCH_FAILED
    fi
+   echo "Check monitoring GPFS connector in case missing down events..."
+   startMonitor $1 $2
+   if [ $? -ne 0 ]; then
+      echo "Can not start monitoring GPFS connector correctly, may miss GPFS connector up/down events..."
+   fi
    isStopped=`/opt/xcat/bin/xdsh $1 "ps -ef | grep tlgpfsmon | grep -v grep | grep -v bash | grep -v ssh | grep -v perl 2>/dev/null | wc -l"`
    isStopped=`echo "$isStopped" | head -1 | tr -d ' ' | cut -d':' -f2`
    if [ $isStopped -eq 0 ]; then
-      # sleep here to wait stop event can be captured and then remove the node in NodeNameList
-      sleep 10
-      updateGPFSMonCond $1 2
       echo "Stopped teal agent on $2 successfully."
       return $SUCCESS
    fi
@@ -236,26 +207,6 @@ if [ $is_enable -eq 0 ]; then
    usage $INVALID_ARG
 fi
 
-# check if node is in service node list
-service_node=`/opt/xcat/bin/nodels $node servicenode.node 2>/dev/null | tr -d ' ' | cut -d: -f2`
-if [[ -z $service_node ]]; then
-   echo "$node is not a valid service node or nodels is not correctly configured! $PROGRAM_NAME failed!"
-   exit $INVALID_SN
-fi
-
-# double check if node is a service node
-is_sn=`/opt/xcat/bin/xdsh $node "ls /etc/xCATSN > /dev/null 2>&1;echo $?" 2>/dev/null | head -1`
-if [ $? -ne 0 ]; then
-   echo "xdsh is not correctly configured or invalid node is specified! $PROGRAM_NAME failed!"
-   exit $CONFIG_FAULT
-fi
-
-is_sn=`echo "$is_sn" | tr -d ' ' | cut -d: -f2`
-if [ $is_sn -eq 1 ]; then
-   echo "$node is not a valid serivce node! $PROGRAM_NAME failed!"
-   exit $INVALID_SN
-fi
-
 # get cluster info for determination
 clusterInfo=`/opt/xcat/bin/xdsh $node /usr/lpp/mmfs/bin/mmlscluster 2>/dev/null`
 if [ $? -ne 0 ]; then
@@ -288,7 +239,6 @@ if [ $? -ne 0 ]; then
    echo "No collector node is designated in $cluster"
    # check if to disable
    if [ $is_enable -eq 2 ];then
-      updateGPFSMonCond $node 2
       echo "Nothing to do, exit...."
       exit $SUCCESS
    fi
@@ -321,7 +271,6 @@ if [ $collectorNode != $gnode ]; then
    if [ $collectorNode != $gnode ]; then
       # if disable action, nothing to do, cause there is no teal agent running on it
       if [ $is_enable -eq 2 ]; then
-         updateGPFSMonCond $node 2
          echo "teal agent is already disabled on $node, nothing to do, exit...."
          exit $SUCCESS
       fi
@@ -343,12 +292,11 @@ fi
 
 # collector node is the specified node
 if [ $is_enable -eq 1 ]; then
-   updateGPFSMonCond $node 1
    echo "$node is already designated as collector node, nothing to do, exit..."
    exit $SUCCESS
 fi
 echo "Disable teal agent on $node"
-stopCollector $node $gnode >/dev/null
+stopCollector $node $gnode 
 if [ $? -ne $SUCCESS ];then
    echo "Disable teal agent failed on $node"
    exit $STOP_FAILED
